// Every fact below comes from the project's GitHub README or the owner's profile README.
// `cover` is either a real screenshot path or `{art: '<name>'}`, a coded cover drawn by
// <ProjectArt> for products whose source or screens are not public.

const repo = (name) => `https://github.com/Ahmadhsn1/${name}`

export const projects = [
	{
		slug: 'easyquran',
		name: 'EasyQuran',
		tagline: 'The Quran app for every Muslim family.',
		type: 'Native study app',
		role: 'Co-lead developer (one of two) · frontend + backend',
		context: 'Built with a Saudi team alongside dedicated QA, content and marketing',
		categories: ['Mobile', 'Product'],
		cover: '/images/projects/easyquran/site.jpg',
		coverPosition: '8% 30%',
		accent: '#e0a24a',
		summary: 'A native Quran study app for Muslim families — the full text with 11+ translations, verse-by-verse recitation with repeat mode, tafseer from Ibn Kathir and Maududi, topic-based browsing, and daily reading goals with streak tracking. Works fully offline after the first download; scholar-certified; completely ad-free.',
		metrics: [
			{value: '10,000+', label: 'families'},
			{value: '4.9★', label: 'Google Play'},
			{value: '11+', label: 'translations'},
			{value: '3', label: 'platforms'},
		],
		features: [
			'Full Quran text with 11+ translations, including Urdu, English, Bengali, Turkish and Indonesian',
			'Verse-by-verse recitation with a repeat mode for memorisation',
			'Scholar-certified tafseer from Ibn Kathir and Maududi',
			'Topic-based browsing and daily reading goals with streaks',
			'Fully offline after the first download, and completely ad-free',
		],
		engineering: [
			{title: 'Offline is a feature, not a fallback', text: 'An offline sync engine means the whole study experience keeps working after the first download — no network, no degraded mode.'},
			{title: 'One release pipeline, three platforms', text: 'Kotlin client and REST backend shipped through an App Store and Play Store release pipeline, with audio streaming for recitation.'},
		],
		stack: {Mobile: ['Kotlin', 'Native Android', 'iOS'], Platform: ['REST backend', 'Offline sync engine', 'Audio streaming'], Release: ['App Store', 'Google Play', 'Web']},
		gallery: [{src: '/images/projects/easyquran/site.jpg', caption: 'easyquran.app — the product site, trusted by 10,000+ families.'}],
		links: [
			{label: 'Product site', url: 'https://easyquran.app/'},
			{label: 'App Store', url: 'https://apps.apple.com/pk/app/easy-quran-urdu-and-english/id6759831556'},
			{label: 'Google Play', url: 'https://play.google.com/store/apps/details?id=com.ahmadshahwaiz.easyquran'},
		],
	},
	{
		slug: 'aria',
		name: 'Aria',
		tagline: 'An AI booking assistant that owns none of the booking logic.',
		type: 'AI booking assistant · Prime Coworking',
		role: 'Product engineering at Prime Coworking',
		context: 'Built on the company’s e-Booking system, a multi-tenant SaaS booking & scheduling product',
		categories: ['AI', 'Web'],
		cover: {art: 'aria'},
		accent: '#8fb3ff',
		summary: 'A conversational booking layer on top of Prime Coworking’s e-Booking product. Customers chat in any language — “need an appointment tomorrow after 5” — and Aria resolves the service and staff, offers real open slots, and books, reschedules or cancels. Aria owns no availability or booking logic: the booking engine stays the single source of truth and Aria is a pure orchestration layer, so the assistant and the product’s own booking widget can never drift apart.',
		metrics: [
			{value: '15', label: 'tool-calling functions'},
			{value: '40', label: 'message bounded history'},
			{value: '4×', label: 'retry with backoff'},
			{value: '1', label: 'public endpoint'},
		],
		features: [
			'Multilingual chat that resolves service, staff and real open slots',
			'Books, reschedules and cancels through the product’s own domain services',
			'Every booking change gated behind an emailed OTP, with a name-and-phone-match fallback',
			'React 19 iframe chat widget — focus-trap accessibility, abort-on-unmount, server-owned state',
			'MongoDB conversation memory with orphan-turn protection',
		],
		engineering: [
			{title: 'The model orchestrates; it never owns the truth', text: 'Each of the 15 tools wraps the exact domain service the e-Booking widget already calls, so there is no second copy of the availability logic for the AI to disagree with.'},
			{title: 'A public endpoint still needs teeth', text: 'The booking API is unauthenticated by design, so mutations are OTP-gated, rate-limited per IP, locked after repeated bad attempts and written to an audit log — and the prompt’s integrity block means a customer can’t talk their way past any of it.'},
			{title: 'Provider-neutral LLM layer', text: 'Gemini 2.5 Flash today, swappable tomorrow — the tool loop never imports a vendor SDK directly.'},
		],
		stack: {Backend: ['NestJS', 'TypeScript', 'MongoDB'], AI: ['Gemini 2.5 Flash', 'Tool calling', 'Provider-neutral layer'], Client: ['React 19', 'Iframe widget']},
		gallery: [],
		links: [],
		privateNote: 'Internal product at Prime Coworking — source is not public.',
	},
	{
		slug: 'retrivo-vault',
		name: 'Retrivo Vault',
		tagline: 'The research assistant that only knows what you’ve read.',
		type: 'AI research assistant · RAG SaaS',
		role: 'Solo · design, build and ship',
		categories: ['AI', 'Web'],
		cover: '/images/projects/retrivo/hero.jpg',
		accent: '#9d8cff',
		summary: 'A production-grade, individual-focused RAG SaaS. Upload contracts, papers and notes, ask questions in plain language, and get streaming answers that cite the exact passage they came from — and say “not in your documents” instead of guessing.',
		metrics: [
			{value: '142', label: 'tests'},
			{value: '3-tier', label: 'chunking cascade'},
			{value: '15s', label: 'token-replay grace'},
			{value: '6', label: 'input formats'},
		],
		features: [
			'PDF, TXT, Markdown, DOCX, CSV and web pages by URL, ingested into a private vault',
			'Streaming, citation-backed chat with match scores and clickable inline sources',
			'Free / Pro / Max plans with trial-aware quotas and Stripe billing',
			'In-app, email and Web Push notifications; activity log and data export',
			'Personal API keys, HMAC-signed webhooks and an OpenAPI spec',
			'Operator admin console: presence, complimentary grants, broadcasts, audit log',
		],
		engineering: [
			{title: 'Isolation is enforced by the index, not the query', text: 'The userId filter is part of the Atlas Vector Search index definition and applied inside the ANN search — post-filtering would let other users’ vectors consume the top-k slots.'},
			{title: 'Chunking that survives hostile documents', text: 'Paragraphs → sentences → fixed-width hard split, with 150-character overlap so a fact straddling a boundary appears whole in at least one chunk.'},
			{title: 'Refresh-token reuse detection with a grace window', text: 'Token families with rotation stamps: a replay within 15s is a client retry, anything older revokes the entire family.'},
		],
		stack: {Backend: ['Node', 'Express', 'MongoDB Atlas Vector Search'], AI: ['Gemini embeddings', 'Gemini generation', 'SSE streaming'], Frontend: ['React', 'TypeScript'], Platform: ['Stripe', 'Web Push', 'OpenAPI']},
		gallery: [
			{src: '/images/projects/retrivo/hero.jpg', caption: 'The promise, and the mechanism behind it — the pipeline is on the hero on purpose.'},
			{src: '/images/projects/retrivo/pipeline.jpg', caption: 'Question → cited answer. Every stage reports itself, with match scores on each citation.'},
			{src: '/images/projects/retrivo/features.jpg', caption: 'A full RAG pipeline, not a wrapper — from parsing to grounded generation.'},
			{src: '/images/projects/retrivo/security.jpg', caption: 'Private by construction — isolation is the filter on every read.'},
		],
		links: [{label: 'GitHub repository', url: repo('Rag-saas-RetrivoVault')}],
	},
	{
		slug: 'leadforge-ai',
		name: 'LeadForge AI',
		tagline: 'Find the right businesses. Understand them. Start the right conversation.',
		type: 'AI sales-intelligence platform',
		role: 'Solo · design, build and ship',
		categories: ['AI', 'Web'],
		cover: '/images/projects/leadforge/dashboard.jpg',
		accent: '#ff8a5c',
		summary: 'Researches local businesses, explains why each one is worth contacting — with citable evidence for every claim — and drafts the message you would actually send. A claim the model can’t trace back to a stored observation is dropped before it ever reaches you.',
		metrics: [
			{value: '198', label: 'automated checks'},
			{value: '6', label: 'scoring dimensions'},
			{value: '46', label: 'design documents'},
			{value: '$0', label: 'to run end to end'},
		],
		features: [
			'Ranked shortlist with a reason for each lead — every claim linked to stored evidence',
			'Observed, Inferred and Unknown labelled explicitly; missing data is never invented',
			'Deterministic scores across ICP fit, opportunity, contactability, maturity, confidence and urgency',
			'Messages validated by a deterministic rule engine and an adversarial model check',
			'Manual channel with one-click wa.me / mailto — nothing sends without approval',
		],
		engineering: [
			{title: 'A claim without a citation doesn’t ship', text: 'The model is asked to explain numbers computed in code; any numbers it returns are discarded.'},
			{title: 'The worker boots the API’s own module graph', text: 'Verification, scoring and outreach run from HTTP and the queue through one implementation, so a lead can never score differently depending on the path.'},
			{title: 'SSRF protection on every redirect hop', text: 'Private, loopback and cloud-metadata ranges are refused before each hop, with byte and time caps.'},
			{title: 'Rate limits reschedule rather than retry', text: 'A daily quota no longer burns five retries in thirty seconds and dead-letters while hours of quota remain.'},
		],
		stack: {Frontend: ['Next.js 15', 'React 19', 'Tailwind', 'Radix', 'TanStack Query'], Backend: ['NestJS 11', 'Prisma 6', 'Zod', 'argon2id'], Data: ['PostgreSQL 16', 'Redis 7', 'BullMQ 5'], AI: ['OpenRouter', 'Strict JSON schemas']},
		gallery: [
			{src: '/images/projects/leadforge/dashboard.jpg', caption: 'Command centre — the day’s pipeline at a glance.'},
			{src: '/images/projects/leadforge/lead-intelligence.jpg', caption: 'Lead intelligence — every claim carries the evidence it came from.'},
			{src: '/images/projects/leadforge/message-studio.jpg', caption: 'Message Studio — drafts grounded in that business’s facts.'},
			{src: '/images/projects/leadforge/leads.jpg', caption: 'Leads table with deterministic six-dimension scoring.'},
			{src: '/images/projects/leadforge/campaign-wizard.jpg', caption: 'Campaign wizard — OpenStreetMap discovery needs no API key.'},
			{src: '/images/projects/leadforge/analytics.jpg', caption: 'Analytics across campaigns and channels.'},
		],
		links: [
			{label: 'Live demo', url: 'https://leadforge-ai-murex.vercel.app'},
			{label: 'GitHub repository', url: repo('leadforge-ai')},
		],
	},
	{
		slug: 'retailflow',
		name: 'RetailFlow',
		tagline: 'Retail software for shops that trade on khata.',
		type: 'Multi-tenant retail SaaS',
		role: 'Solo · design, build and ship',
		categories: ['Web', 'Product'],
		cover: {art: 'retailflow'},
		accent: '#7dd3a8',
		summary: 'A multi-tenant POS, inventory and credit-ledger platform for South Asian shops — barcode billing, weighted-average costing, khata credit ledgers and shift reconciliation, on a Postgres schema where every tenant is isolated by Row Level Security and every rupee is an integer.',
		metrics: [
			{value: '231', label: 'tests'},
			{value: '35', label: 'tables'},
			{value: '92', label: 'migrations'},
			{value: '22', label: 'permissions'},
		],
		features: [
			'Barcode billing with mixed payment on one bill — cash, khata and JazzCash/Easypaisa',
			'Shifts with declared float and expected-vs-actual variance, reconciled to the paisa',
			'Multi-unit inventory (carton → packet → piece) with Urdu product names',
			'Partial goods receipt and a weighted-average costing engine with historical cost snapshots',
			'Khata ledgers with DB-enforced credit limits and aging buckets',
			'Owner / manager / cashier roles over 22 permissions, with PIN counter hand-off',
		],
		engineering: [
			{title: 'Money is never a float', text: 'Every amount is stored as an integer and the cash drawer reconciles to the paisa before anyone goes home.'},
			{title: 'One RPC, one transaction', text: 'A sale lands completely — stock, money, ledger, invoice number — or not at all. The drawer and the shelf can never disagree.'},
			{title: 'Tenants isolated by the database', text: 'SELECT-only RLS for clients and no client write policy on any financial table; writes go through permission-checked RPCs.'},
		],
		stack: {App: ['Next.js 15', 'React 19 Server Components', 'TypeScript (strict)', 'Tailwind'], Data: ['Supabase Postgres', 'Row Level Security', '41 RPCs'], Ops: ['56 API routes', 'Resend', 'WhatsApp Cloud API']},
		gallery: [],
		links: [
			{label: 'Live demo', url: 'https://shop-management-liard.vercel.app/'},
			{label: 'GitHub repository', url: repo('retailflow-saas')},
		],
	},
	{
		slug: 'notemind',
		name: 'NoteMind',
		tagline: 'Notes that think with you.',
		type: 'AI knowledge platform',
		role: 'Solo · design, build and ship',
		categories: ['AI', 'Web'],
		cover: '/images/projects/notemind/dashboard.jpg',
		accent: '#b9a4ff',
		summary: 'An AI-augmented MERN note-taking platform engineered to production standards: semantic search and cited Q&A across your notes, SM-2 flashcards generated from raw notes, and a live force-directed graph of wikilinked notes — free, with no ads and no paid tier.',
		metrics: [
			{value: '173', label: 'tests'},
			{value: '0', label: 'vulnerabilities'},
			{value: '768-d', label: 'embeddings'},
			{value: 'PWA', label: 'offline reads'},
		],
		features: [
			'Tiptap editor with slash commands, tasks, image upload and [[wikilinks]]',
			'Cross-note Q&A streamed token by token, with cited sources',
			'Semantic search with automatic keyword fallback during outages',
			'SM-2 spaced repetition, streaks and an activity calendar',
			'Version history on every save — restores are themselves undoable',
			'Admin surface with live WebSocket stats, moderation and an audit log',
		],
		engineering: [
			{title: 'Sessions are verified, not merely decoded', text: 'The user is loaded on every request, so deletion and suspension take effect now — and a password reset revokes every older token.'},
			{title: 'The test suite is validated, not assumed', text: 'Proven by re-introducing real, previously-shipped bugs one at a time and confirming each one is caught.'},
			{title: 'A Gemini key pool with real quota semantics', text: 'Round-robins across keys with per-key cooldowns that respect daily vs per-minute limits.'},
		],
		stack: {Frontend: ['React 19', 'Tiptap', 'd3-force', 'PWA'], Backend: ['Express 5', 'MongoDB', 'Socket.IO'], AI: ['Google Gemini', 'Embeddings', 'SSE']},
		gallery: [
			{src: '/images/projects/notemind/dashboard.jpg', caption: 'Dashboard — notes, streaks and today’s reviews.'},
			{src: '/images/projects/notemind/graph-view.jpg', caption: 'Graph view — a live force-directed map of wikilinked notes.'},
			{src: '/images/projects/notemind/landing.jpg', caption: 'The public marketing site, served from the same SPA build.'},
		],
		links: [
			{label: 'Engineering dossier', url: 'https://ahmadhsn1.github.io/notemind-ai/'},
			{label: 'GitHub repository', url: repo('notemind-ai')},
		],
	},
	{
		slug: 'fitmind-ai',
		name: 'FitMind AI',
		tagline: 'A coach that re-plans around you — and asks before it changes anything.',
		type: 'Adaptive AI fitness coaching',
		role: 'Solo · Android + backend',
		categories: ['AI', 'Mobile'],
		cover: {art: 'fitmind'},
		accent: '#ffc56e',
		summary: 'A Kotlin/Jetpack Compose Android client on a Flask + MySQL backend, with a Gemini-powered coach that proposes changes to your training and nutrition plan — and never applies one without your say-so.',
		metrics: [
			{value: '941', label: 'tests'},
			{value: '8', label: 'decision engines'},
			{value: '43', label: 'endpoints'},
			{value: 'R8', label: 'signed APK + AAB'},
		],
		features: [
			'A week of workouts and meals sized to your TDEE — and your food budget',
			'Form-efficiency engine corrects logged calories by rep quality, not just duration',
			'Behavioural classifier reads weeks of sessions: consistent, sporadic, overreaching, declining',
			'Plan-change proposals you approve or revert, fingerprinted against the data they used',
			'An AI coach that answers with your own numbers',
		],
		engineering: [
			{title: 'Stale evidence retires a proposal', text: 'Each proposal records a fingerprint of its data; if the evidence moves on, it is retired rather than silently applied.'},
			{title: 'Honest about what it doesn’t know', text: 'Predictions are gated on data sufficiency — goal projection declines to draw a confident line through three weigh-ins.'},
			{title: 'Architecture that is enforced, not described', text: 'presentation has zero imports from data, and domain has zero imports from either.'},
		],
		stack: {Android: ['Kotlin 2.2', 'Jetpack Compose', 'Material 3', 'Hilt', 'Room', 'WorkManager'], Backend: ['Flask', 'SQLAlchemy', 'Alembic', 'MySQL 8', 'Gunicorn'], AI: ['Google Gemini']},
		gallery: [],
		links: [],
		privateNote: 'Repository is private — walkthrough available on request.',
	},
	{
		slug: 'copper-larder',
		name: 'The Copper Larder',
		tagline: 'Hannah — an AI front-of-house concierge for hospitality sites.',
		type: 'Streaming AI restaurant host',
		role: 'Solo · design, build and ship',
		categories: ['AI', 'Web'],
		cover: '/images/projects/larder/hero.jpg',
		accent: '#d98b5f',
		summary: 'A conversational menu and booking assistant for a modern British bistro — streamed from the model, grounded in real data, and wrapped in the cost controls, guardrails and abuse protection a public LLM endpoint actually needs.',
		metrics: [
			{value: '8', label: 'stage request pipeline'},
			{value: '~19', label: 'zero-token intercepts'},
			{value: '0', label: 'raw IPs stored'},
			{value: 'SSE', label: 'streamed replies'},
		],
		features: [
			'Streaming replies with a proactive, time-aware greeting',
			'Rich dish and info cards built only from typed restaurant data',
			'Conversation-wide dietary lock — “I’m vegan” in message 2 still holds in message 20',
			'Inline callback lead capture feeding an owner dashboard',
			'Accessible dialog: focus trap, aria-live streaming, reduced motion honoured',
		],
		engineering: [
			{title: 'The model is the last resort, not the first', text: 'Session caps, complaint handoff, regex intercepts and an exact-match cache answer first; only stage 7 costs a token.'},
			{title: 'Guardrails that correct the model', text: 'A reply that confirms availability is caught, rewritten with a correction, and blocked from the cache.'},
			{title: 'It always degrades gracefully', text: 'Model down, rate-limited or key missing — every path returns a warm, on-brand message and a callback card.'},
		],
		stack: {App: ['Next.js 16', 'React 19', 'TypeScript', 'Tailwind v4'], AI: ['Gemini 2.0 Flash', '@google/genai', 'SSE'], Data: ['Supabase Postgres', 'RLS', 'Zod']},
		gallery: [
			{src: '/images/projects/larder/hero.jpg', caption: 'The bistro site — a full marketing experience around the concierge.'},
			{src: '/images/projects/larder/chat.jpg', caption: 'Hannah streaming a reply with rich dish cards.'},
			{src: '/images/projects/larder/menu.jpg', caption: 'Editorial menu — the single source of truth the model is handed.'},
			{src: '/images/projects/larder/callback.jpg', caption: 'Inline callback capture, validated client- and server-side.'},
		],
		links: [
			{label: 'Live site', url: 'https://copper-larder.vercel.app'},
			{label: 'GitHub repository', url: repo('larder-concierge-ai')},
		],
	},
	{
		slug: 'mindscribe',
		name: 'MindScribe',
		tagline: 'Journaling that treats your words as sensitive data.',
		type: 'Privacy-first Android journal',
		role: 'Solo · Android',
		categories: ['Mobile', 'Product'],
		cover: '/images/projects/mindscribe/banner.svg',
		accent: '#9ec5a7',
		summary: 'A native Android journaling app built on one conviction: what people write about their own lives is sensitive data. The journal locks independently of the phone, writing never blocks on the network, and journaling is guided rather than blank-page.',
		metrics: [
			{value: '25', label: 'classes'},
			{value: '3,857', label: 'lines of Java'},
			{value: 'AES-256', label: 'encrypted prefs'},
			{value: '14', label: 'guided prompts'},
		],
		features: [
			'Biometric unlock with PIN fallback — salted SHA-256, the PIN is never stored',
			'Voice dictation, image attachments, one-line mode and time capsules',
			'Real-time list across devices with composable category, date and text filters',
			'Luna daily prompts, writing streaks and a mood distribution chart',
			'Owner-only Firestore and Storage rules committed to the repo',
		],
		engineering: [
			{title: 'Offline is a feature, not a fallback', text: 'Notes commit to Firestore’s local cache instantly; uploads are handed to WorkManager and finish after process death or reboot.'},
			{title: 'Deliberately legible', text: 'Plain Java with ViewBinding — no reactive framework, no DI container — so the data flow reads end to end.'},
		],
		stack: {Android: ['Java 8', 'Material 3', 'ViewBinding', 'WorkManager'], Security: ['BiometricPrompt', 'EncryptedSharedPreferences'], Backend: ['Firebase Auth', 'Cloud Firestore', 'Cloud Storage']},
		gallery: [{src: '/images/projects/mindscribe/banner.svg', caption: 'MindScribe — privacy-first journaling for Android.'}],
		links: [
			{label: 'Download APK', url: `${repo('MindScribe-android-app')}/releases/latest`},
			{label: 'GitHub repository', url: repo('MindScribe-android-app')},
		],
	},
	{
		slug: 'spendsmart',
		name: 'SpendSmart',
		tagline: 'Every edit lands on every device before the keyboard closes.',
		type: 'Real-time Android expense tracker',
		role: 'Solo · Android',
		categories: ['Mobile', 'Product'],
		cover: '/images/projects/spendsmart/banner.jpg',
		accent: '#6fcf97',
		summary: 'A personal-finance tracker for Android with no backend server: the app talks to Cloud Firestore directly over an authenticated channel, so reads are live — and the security rules are the entire authorization layer.',
		metrics: [
			{value: '0', label: 'backend servers'},
			{value: '8', label: 'dependency lines'},
			{value: '7', label: 'validated categories'},
			{value: 'Live', label: 'snapshot sync'},
		],
		features: [
			'Email/password auth with a splash router — returning users never see a login form',
			'Full CRUD with partial-field updates that never clobber a document',
			'Live dashboard stats folded from the expense stream, never stored counters',
			'Instant client-side search across title and category',
			'Designed empty states and guarded deletes throughout',
		],
		engineering: [
			{title: 'The database is the security boundary', text: 'firestore.rules is a deny-by-default whitelist: schema-validated writes, owner-only reads — a patched APK still can’t read anyone else’s spending.'},
			{title: 'Eight dependencies, every one used', text: 'Plain Java 8 on AndroidX and Material 3 — no DI framework and no reactive library.'},
		],
		stack: {Android: ['Java 8', 'Material 3', 'AndroidX'], Backend: ['Firebase Auth', 'Cloud Firestore', 'Security Rules'], Tooling: ['Android CI']},
		gallery: [
			{src: '/images/projects/spendsmart/dashboard.jpg', caption: 'Dashboard — time-aware greeting, live totals, recent rows.', tall: true},
			{src: '/images/projects/spendsmart/expenses.jpg', caption: 'All expenses — instant search across title and category.', tall: true},
			{src: '/images/projects/spendsmart/add-expense.jpg', caption: 'Add expense — rupee-prefixed amount and native date picker.', tall: true},
			{src: '/images/projects/spendsmart/login.jpg', caption: 'Login — Material 3 fields with inline validation.', tall: true},
		],
		links: [{label: 'GitHub repository', url: repo('SpendSmart')}],
	},
	{
		slug: 'fittrack',
		name: 'FitTrack',
		tagline: 'Gym management, without the spreadsheet.',
		type: 'Gym management dashboard',
		role: 'Solo · front end & design system',
		categories: ['Web', 'Product'],
		cover: '/images/projects/fittrack/dashboard.jpg',
		accent: '#ff7a59',
		summary: 'An admin dashboard that answers “how is my gym doing right now?” — members, memberships, attendance, trainers and payments — built as a single-page React app with a hand-authored design system and zero UI dependencies.',
		metrics: [
			{value: '8', label: 'routes'},
			{value: '0', label: 'UI dependencies'},
			{value: '194 kB', label: 'gzipped'},
			{value: '2', label: 'themes'},
		],
		features: [
			'Dashboard KPIs derived from live data — nothing hardcoded',
			'Members with full CRUD, compound filtering and drill-through detail views',
			'Plans as first-class entities with live member counts',
			'Daily attendance roster with optimistic toggles',
			'Dual-theme token system that re-themes the charts too',
		],
		engineering: [
			{title: 'A design system authored from scratch', text: 'Every component sits on a CSS custom-property token layer — knowing how a design system works matters more than importing one.'},
			{title: 'Scope, stated honestly', text: 'A complete front end on an isolated in-memory data layer, so swapping in a REST or Supabase backend is a provider-level change.'},
		],
		stack: {Frontend: ['React 19', 'Vite', 'React Router', 'Recharts'], Design: ['CSS design tokens', 'Dual theme', 'No UI kit']},
		gallery: [
			{src: '/images/projects/fittrack/dashboard.jpg', caption: 'The answer screen — live KPIs, weekly attendance, revenue roll-up.'},
			{src: '/images/projects/fittrack/members.jpg', caption: 'Members — compound search, status and plan filters.'},
			{src: '/images/projects/fittrack/member-details.jpg', caption: 'Member details — the 360° view with payment history.'},
			{src: '/images/projects/fittrack/payments.jpg', caption: 'Payments — every roll-up derived from records.'},
		],
		links: [{label: 'GitHub repository', url: repo('fittrack-gym-management')}],
	},
]

export const projectCategories = ['All', 'AI', 'Web', 'Mobile', 'Product']

export const totals = {
	projects: projects.length,
	tests: 142 + 198 + 231 + 173 + 941,
}
